# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: rbx1_arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_1_base_shoulder
    - joint_2_shoulder_arm
    - joint_3_arm_upper_forearm
    - joint_4_upper_forearm_forearm
    - joint_5_forearm_wrist
    - joint_6_wrist_hand
    - gripper_idol_gear_joint
    - gripper_servo_gear_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - joint_1_base_shoulder
    - joint_2_shoulder_arm
    - joint_3_arm_upper_forearm
    - joint_4_upper_forearm_forearm
    - joint_5_forearm_wrist
    - joint_6_wrist_hand
  gains:
    joint_1_base_shoulder:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_2_shoulder_arm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_3_arm_upper_forearm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_4_upper_forearm_forearm:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_5_forearm_wrist:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_6_wrist_hand:
      p: 100
      d: 1
      i: 1
      i_clamp: 1