# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/



#Config 1
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

#Config 2
# language: en_core_web_md
# pipeline:
# - name: "SpacyNLP"
# - name: "SpacyTokenizer"
# - name: "SpacyFeaturizer"
# - name: "RegexFeaturizer"
# - name: "CRFEntityExtractor"
# - name: "EntitySynonymMapper"
# - name: "SklearnIntentClassifier"  

#Config 3
# language: en
# pipeline:
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: "char_wb"
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     use_masked_language_model: True
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100

#Config 4 
# language: en
# pipeline:
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: "char_wb"
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#   - name: EntitySynonymMapper
#   - name: "KeywordIntentClassifier"
#     case_sensitive: True

